server:
  port: 8080
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/secondbook?useUnicode=true&amp;characterEncodeing=UTF-8&amp;useSSL=false&amp;serverTimezone=GMT
    username: wiiii
    password: 20010807

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/books/BookInfoMapper.xml
  type-aliases-package: com.books.domain
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true